STRIPE_PUBLISHABLE_KEY = ENV["STRIPE_PUBLISHABLE_KEY"] or raise "Required Environment Var: STRIPE_PUBLISHABLE_KEY"
STRIPE_SECRET_KEY = ENV["STRIPE_SECRET_KEY"] or raise "Required Environment Var: STRIPE_SECRET_KEY"
