default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dibstarter_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: dibstarter_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: dibstarter_production
